### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by shaohaolin** [johnpapa/angular2-tour-of-heroes#52]
Can you add unit testing?

Thank you!

**Comment by jodytate** [comment]
I'm curious about this as well and would be interested in helping if @johnpapa thinks adding tests wouldn't overload the purpose of the tour. 

My first guess, though, is that this repo could be a useful place for the community to see best practices regarding unit tests for an Angular 2 app. Maybe tests are planned as part of an upcoming chapter of the hero tutorial in the Angular docs?

**Comment by johnpapa** [comment]
Good questions, but let me clarify a few things. 

This repo is really a testing ground for my work on the ToH (Tour of Heroes). So what you see here may not be what is in the official one. That's not good or bad, just want to be clear this is not exactly the same.

Testing is important and there are great testing chapters in the angular.io docs. That is the best place to find those right now.  

I will continue creating more samples, some with testing, some with AM2, some with other features. This is a bit freeform right now.

I'm currently working on a course for Pluralsight on A2, so that has my attention right now over new repos and samples. I think you will like what is in there :)

The style guide is coming ... I've made some significant progress on the basics of it. Just trying to find the right way to open the doors and nail down the last few issues I have to resolve before doing so.

**Comment by jodytate** [comment]
thanks @johnpapa for the update and clarifications.

**Comment by antonybudianto** [comment]
@shaohaolin , you can take a look at my [starter](https://github.com/antonybudianto/angular2-starter) for unit testing (with TypeScript coverage!)

**Comment by antonybudianto** [comment]
@johnpapa , I'm one fan of your style guide, currently I'm following this [ng2 style guide](https://github.com/mgechev/angular2-style-guide), how do you think? :smile:

**Comment by johnpapa** [comment]
Havent looked it over yet.

I'm working on one, due out by ngConf

**Comment by antonybudianto** [comment]
@johnpapa , I'm looking forward for yours then :+1:

**Comment by shaohaolin** [comment]
@antonybudianto Your link is not working . 
@johnpapa Thank you for the update!

**Comment by antonybudianto** [comment]
@shaohaolin , updated

**Comment by johnpapa** [comment]
Thanks.

I'm sure other opinions are good to look at too. My first cut will be the things that are more fundamental. Things we can safely say are good patterns. The rest will come with more experience and time with it.

**Comment by akajains** [comment]
I am following this request for unit tests. @johnpapa love your examples on github.

Can someone could point to a nice article about testing observable (angular2)? Thanks heaps.

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI and it has testing

**Comment by dman777** [comment]
I only see a small e2e test in the CLI version...I do not see any unit tests.
