### ISSUE TITLE
use `Location.back()` instead of `window.history.back()`

### ISSUE THREAD

**Issue by SamVerschueren** [johnpapa/angular2-tour-of-heroes#66]
I was just wondering if it would make more sense to use [Location.back()](https://angular.io/docs/ts/latest/api/common/index/Location-class.html#!#back-anchor) instead of `window.history.back()` on [this](https://github.com/johnpapa/angular2-tour-of-heroes/blob/master/app/hero-detail.component.ts#L27) line. The latter seems tightly coupled with the environment, in this case the browser.

**Comment by tobiaghiraldini** [comment]
In addition, in my case the back button led me to the correct URL but the views did not display any data at all. Like the router didn't make the associated components to call the ngOnInit method.
Did you experience this behaviour as well?
EDIT:
(I'm following the tutorial and using router-deprecated instead of the new alpha router component)

**Comment by johnpapa** [comment]
sure. you can choose your own path
